## play level vars
- name: Demo on play variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - debug:
        msg: URL = {{ URL }}
## task vars
- name: Demo on task level variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.example.com
## cli vars
- name: Demo on CLI variables
  hosts: all
  tasks:
    - name:
      debug:
        msg: URL1 = {{ URL1 }}