## play level vars
- name: Demo on play variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - debug:
        msg: URL = {{ URL }}
## task vars
- name: Demo on task level variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.example.com
## cli vars
- name: Demo on CLI variables
  hosts: all
  tasks:
    - name:
      debug:
        msg: URL1 = {{ URL1 }}
## vars from inv file
- name: Demo on variables from inventory file
  hosts: all
  tasks:
    - name: Demo on vars from inv file
      debug:
        msg: URL2 = {{ URL2 }}
## vars from files
- name: Demo on variables from file
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Demo on vars from file
      debug:
        msg: URL_FILE = {{ URL_FILE }}
## vars from prompt
- name: Demo on variables from prompt
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: no
  tasks:
    - name: Print URL
      debug:
        msg: URL= {{ URL }}