- name: Demo on facts
  hosts: all
  gather_facts: no
  tasks:
    - name: Print Hostname
      debug:
        msg: HostName = {{ ansible_hostname }}, OS family = {{ ansible_os_family }}, ID = {{ ansible_user_id }}
