- name: Demo on run time vars
  hosts: all
  tasks:
    - name: Grab uptime
      shell: uptime
      register: OUT
    - name: Print Uptime
      debug:
        msg: "{{OUT_stdout}}"
    - name: set a variable
      set-fact:
        UPTIME_OUTPUT: "{{OUT.stdout}}"
    - name: print uptime
      debug:
        msg: "Uptime={{UPTIME_OUTPUT}}"